fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in pyproject.toml
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--ignore-words-list", "crate,NotIn"]

  - repo: local
    hooks:
      - id: lint-rs
        name: Lint Rust
        entry: make lint-rs
        types: [rust]
        language: system
        pass_filenames: false
      - id: lint-py
        name: Lint Python
        entry: make lint-py
        types: [python]
        language: system
        pass_filenames: false
      - id: test
        name: Test
        entry: make test
        types: [rust]
        language: system
        pass_filenames: false
